### ISSUE TITLE
DataverseTV "design" is too plain, from the early 90s

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse-tv#1]
*Sigh*. I'm an old Perl hacker originally. Not a front end designer. My "designs" look like they're from the early 90s:

![Screen Shot 2020-02-27 at 2 12 50 PM](https://user-images.githubusercontent.com/21006/75478038-414a9100-596b-11ea-942b-74dae046c408.png)

**Comment by atrisovic** [comment]
Fixed with (now merged) PR https://github.com/IQSS/dataverse-tv/pull/2 :)
