### ISSUE TITLE
DataverseTV is down, videos not shown due to CORS error

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse-tv#3]
When I built DataverseTV I took advantage of the fact that Google was allowing CORS on Google Spreadsheet downloads but recently CORS support was taken away. This means that DataverseTV is effectively down. No videos are shown (as in the screenshot below) and a CORS error can be seen on the Javascript console:

<img width="1170" alt="Screen Shot 2020-09-10 at 10 08 37 AM" src="https://user-images.githubusercontent.com/21006/92742954-1a274000-f34e-11ea-8819-aca7cc441879.png">

In a thread at https://support.google.com/docs/thread/56845119?hl=en some seems to have figured out an alternative URL that might work and still support CORS but it probably makes more sense to switch over to the dataverse-installations model where we commit the data into the repo rather than loading it live from a third party site (Google Spreadsheets).

DataverseTV hasn't been advertised widely but I did announce it at https://groups.google.com/g/dataverse-community/c/kJEVDqK9Yf0/m/mpPbVFxKCgAJ and it has been linked to a few times on that mailing list. Especially with all the great videos from the 2020 Dataverse Community Meeting, I've been thinking it would be great to include this content and future recordings in our work-from-home world. 😄

**Comment by erikbuunk** [comment]
I am downloading the Spreadsheet with Python for the metrics dashboard. So we could use that to write as TSV somewhere, or Dataverse TE could read it from the github repo of the dashboard (you could use https://github.com/IQSS/iqss-metrics-dashboard/blob/master/assets/data/dataverse_tv.tsv)

**Comment by atrisovic** [comment]
We can close this one? It's no longer a problem :)

**Comment by atrisovic** [comment]
I'll close this as it's now outdated.
